const BOOLEAN_ATTRIBUTES = [
  'common-form.disabled' ,
  'common.hidden',
  'common.itemscope',
  'details.open',
  'dialog.open',
  'form.novalidate' ,
  'iframe.allowfullscreen',
  'iframe.allowusermedia',
  'img.ismap',
  'input.checked' ,
  'input.multiple' ,
  'media.autoplay  ',
  'media.controls ',
  'media.loop',
  'media.muted',
  'menuitem.checked',
  'menuitem.default',
  'menuitem.disabled',
  'object.typemustmatch',
  'ol.reversed',
  'option.selected',
  'script.async',
  'script.defer',
  'select.multiple',
  'shared-form.autofocus' ,
  'shared-form.formnovalidate' ,
  'shared-form.readonly' ,
  'shared-form.required' ,
  'track.default',
  'video.playsinline',
];

export default BOOLEAN_ATTRIBUTES;
